services:
  ubuntu:
    build: .
    container_name: ubuntu24-04
    volumes:
      - ubuntu_data:/home/ubuntu
    tty: true
    privileged: true  # necessário para iptables funcionar corretamente
volumes:
  ubuntu_data: